In [4]:
numberOfStudents = 20
averageGrade = 67.46

class(numberOfStudents)
class(averageGrade)

numberOfStudents
averageGrade

[1] "numeric"

[1] "numeric"

[1] 20

[1] 67.46

In [5]:
numberOfStudents = 20L 
MSCstudent = TRUE

class(numberOfStudents)
class(MSCstudent)

[1] "integer"

[1] "logical"

In [8]:
studentGrades = c(74.5, 85.3, 92.7)
studentGrades
studentGrades[2]
studentGrades = c(studentGrades,"100.3")

[1] 74.5 85.3 92.7

[1] 85.3

In [9]:
lastName = c("Hofmann","Nolan", "Gray")
lastName = c(lastName, "Tracey")
lastName

lastName[2] #shows individual value   2nd place value
lastName[3] #shows individual value   3rd place value

[1] "Hofmann" "Nolan"   "Gray"    "Tracey"

[1] "Nolan"

[1] "Gray"

In [10]:
resultList = list(names = lastName, grades = studentGrades)
resultList

resultList$names  #Lists only one vector within the list
resultList$names[2] # Lists second entry of the names vector

$names
[1] "Hofmann" "Nolan"   "Gray"    "Tracey"

$grades
[1] "74.5"  "85.3"  "92.7"  "100.3"

[1] "Hofmann" "Nolan"   "Gray"    "Tracey"

[1] "Nolan"

In [11]:
newMatrix = matrix(c(1,2,3,4,5,6,9, 11,10), byrow = F, ncol = 3)
newMatrix

     [,1] [,2] [,3]
[1,] 1    4     9
[2,] 2    5    11
[3,] 3    6    10

In [12]:
studentResultsDataFrame = data.frame(names = lastName, grades = studentGrades)
studentResultsDataFrame

  names   grades
1 Hofmann 74.5
2 Nolan   85.3
3 Gray    92.7
4 Tracey  100.3

In [13]:
mean(studentResultsDataFrame$grades)

Warning message in mean.default(studentResultsDataFrame$grades):
“argument is not numeric or logical: returning NA”

[1] NA

In [14]:
studentGrades = c(74.5, 85.3, 92.7, NA)
studentGrades

is.na(studentGrades)

[1] 74.5 85.3 92.7   NA

[1] FALSE FALSE FALSE  TRUE

In [17]:
mean    #this shows some general info
methods(mean) # shows the methods
?mean
getAnywhere(mean.default)
x <- c(0:10, 50)
x
xm <- mean(x)
c(xm, mean(x, trim = 0.10))

function (x, ...)
UseMethod("mean")
<bytecode: 0x5574a200b968>
<environment: namespace:base>

[1] mean.Date        mean.default     mean.difftime    mean.POSIXct
[5] mean.POSIXlt     mean.quosure*    mean.vctrs_vctr*
see '?methods' for accessing help and source code

A single object matching ‘mean.default’ was found
It was found in the following places
  package:base
  registered S3 method for mean from namespace base
  namespace:base
with value

function (x, trim = 0, na.rm = FALSE, ...)
{
    if (!is.numeric(x) && !is.complex(x) && !is.logical(x)) {
        warning("argument is not numeric or logical: returning NA")
        return(NA_real_)
    }
    if (isTRUE(na.rm))
        x <- x[!is.na(x)]
    if (!is.numeric(trim) || length(trim) != 1L)
        stop("'trim' must be numeric of length one")
    n <- length(x)
    if (trim > 0 && n) {
        if (is.complex(x))
            stop("trimmed means are not defined for complex data")
        if (anyNA(x))
            return(NA_real_)
        if (trim >= 0.5)
            return(stats::median(x, na.rm = FALSE))
        lo <- floor(n * trim) + 1
        hi <- n + 1 - lo
        x <- sort.int(x, partial = unique(c(lo, hi)))[lo:hi]
    }
    .Internal(mean(x))
}
<bytecode: 0x5574a453fd78>
<environment: namespace:base>

 [1]  0  1  2  3  4  5  6  7  8  9 10 50

[1] 8.75 5.50

mean                   package:base                    R Documentation

_A_r_i_t_h_m_e_t_i_c _M_e_a_n

_D_e_s_c_r_i_p_t_i_o_n:

     Generic function for the (trimmed) arithmetic mean.

_U_s_a_g_e:

     mean(x, ...)

     ## Default S3 method:
     mean(x, trim = 0, na.rm = FALSE, ...)

_A_r_g_u_m_e_n_t_s:

       x: An R object.  Currently there are methods for numeric/logical
          vectors and date, date-time and time interval objects.
          Complex vectors are allowed for ‘trim = 0’, only.

    trim: the fraction (0 to 0.5) of observations to be trimmed from
          each end of ‘x’ before the mean is computed.  Values of trim
          outside that range are taken as the nearest endpoint.

   na.rm: a logical evaluating to ‘TRUE’ or ‘FALSE’ indicating whether
          ‘NA’ values should be stripped before the computation
          proceeds.

     ...: further arguments passed to or from other methods.

_V_a_l_u_e:

     If ‘trim’ is zero (the default), the arithmetic mean of the values
     in ‘x’ is computed, as a numeric or complex vector of length one.
     If ‘x’ is not logical (coerced to numeric), numeric (including
     integer) or complex, ‘NA_real_’ is returned, with a warning.

     If ‘trim’ is non-zero, a symmetrically trimmed mean is computed
     with a fraction of ‘trim’ observations deleted from each end
     before the mean is computed.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

_S_e_e _A_l_s_o:

     ‘weighted.mean’, ‘mean.POSIXct’, ‘colMeans’ for row and column
     means.

_E_x_a_m_p_l_e_s:

     x <- c(0:10, 50)
     xm <- mean(x)
     c(xm, mean(x, trim = 0.10))